### ISSUE TITLE
Concurrency bug causing duplicate raids(?)

### ISSUE THREAD

**Issue by lamperi** [raidikalu/raidikalu#28]
![image](https://user-images.githubusercontent.com/777453/47648157-d6742480-db81-11e8-9b42-34ecec27d389.png)

There is likely a concurrency issue which allows multiple raids to be enrolled to same gym.

**Comment by MzHub** [comment]
Thanks. This should be fixed in https://github.com/raidikalu/raidikalu/commit/d2eb70b4d181f67e9084c900e684c4e1fbfb47c1 but it has not been fully tested or released yet.
